version: "3.9"

volumes:
  static_volume:

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file: "main/.env.docker2"
    ports:
      - "5432:5432"
    
  education:
    build:
      context: ./main
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - education

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./main
    command: celery -A main worker --loglevel=info
    depends_on:
      - redis
      - postgres-db
    env_file: "main/.env.docker3"

  celery-beat:
    build:
      context: ./main
    command: celery -A main beat --loglevel=info
    depends_on:
      - redis
      - postgres-db
    env_file: "main/.env.docker3"