# Generated by Django 4.1.13 on 2024-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0005_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='day',
            field=models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СУББ', 'Суббота')], max_length=355),
        ),
    ]
